branches:
  only:
  - master
  - stable
language: python
python:
    - "3.6"
before_install:
    - pip install --user awscli
install:
    - sh build.sh
    - cd public
    - aws s3 sync . ${BUCKET_URI}
